//
// Created by berke on 3/11/2026.
//

#ifndef RAYCAST_RENDERER_CONFIG_H
#define RAYCAST_RENDERER_CONFIG_H


#define SCREEN_WIDTH 1080
#define SCREEN_HEIGHT 960

#define RAY_SIZE 0.1f
#define MAX_RAY_LENGTH 1500

#define FOV 120
#define RAY_COUNT SCREEN_WIDTH

#define PLAYER_SPEED 5
#define PLAYER_ROT_SPEED 0.05f
#define PLAYER_FRICTION .3f
#define PLAYER_SCALE 15

#define WALL_HEIGHT 100
#define MAX_WALL_OVERLAP 4

#define FPS 60
#define FRAME_DELAY (1000 / FPS)

#endif //RAYCAST_RENDERER_CONFIG_H