//
// Created by berke on 3/11/2026.
//

#ifndef RAYCAST_RENDERER_CONFIG_H
#define RAYCAST_RENDERER_CONFIG_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define FPS 60
#define FRAME_DELAY (1000 / FPS)

#endif //RAYCAST_RENDERER_CONFIG_H