//
// Created by berke on 3/11/2026.
//

#ifndef RAYCAST_RENDERER_CONFIG_H
#define RAYCAST_RENDERER_CONFIG_H


#define SCREEN_WIDTH 980
#define SCREEN_HEIGHT 800

#define RAY_SIZE 0.1f
#define MAX_RAY_LENGTH 1500

#define FOV 60
#define RAY_COUNT 200

#define PLAYER_SPEED 5
#define PLAYER_ROT_SPEED 0.05f
#define PLAYER_FRICTION .3f
#define PLAYER_SCALE 15

#define FPS 60
#define FRAME_DELAY (1000 / FPS)

#endif //RAYCAST_RENDERER_CONFIG_H